### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by maxgerhardt**
Worksaround https://github.com/platformio/platformio-core/issues/4590, makes platform more robust

Uses same type of less than expression than in e.g. 

https://github.com/platformio/platform-ststm32/blob/5cc07cbc7d94e3f4bbe4feb66660174673e458ce/platform.json#L73-L76

### CODE REVIEW

**Comment by p3p** [comment]
Well this is a mess, releasing broken packages is not the best idea, thanks for bringing it to my attention I wouldn't have noticed for a while without clearing the caches and deleting the installed platform

**Comment by maxgerhardt** [comment]
I've converted this PR to a draft because I hope to get it fixed at the source, either by retraction or fixing of the broken GCC 11.x package -- though in any case it'd be better for the future to have the used compiler version either limited or fixed to a version.

So let's just wait for a bit more. It "just" affects people who've newly downloaded Marlin anyways, and the fix I posted in the community topic should unblock them for now.

**Comment by p3p** [comment]
I'd rather not stop autoupdating the toolchain, but if we can't trust even a toolchain release you are probably correct that it should just use a specific version even if this is fixed upstream.

**Comment by maxgerhardt** [comment]
Per https://registry.platformio.org/tools/platformio/toolchain-gccarmnoneeabi/versions the incomplete 11.x version has been removed from the registry (renamed to `toolchain-gccarmnoneeabi-teensy`) and thus compilation should be restored without any modifications.

So if auto-updating toolchains are still wanted, also no modifications need to be done here.

**Pull request closed without merging**
